// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufGOvBV0gwdu5hJmu5hqA6s5CIPgXsuE',
    appId: '1:30448934988:android:c9d3bb04222e68e80394e9',
    messagingSenderId: '30448934988',
    projectId: 'driptock-dp',
    storageBucket: 'driptock-dp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCahIOGGcQiuA8Yx4DyGlU3a3n7tgBjPUc",
      authDomain: "notice-fedc3.firebaseapp.com",
      projectId: "notice-fedc3",
      storageBucket: "notice-fedc3.appspot.com",
      messagingSenderId: "971157069539",
      appId: "1:971157069539:web:3d8c6377137c9aef5cefd6");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLd2KV6bsKjUs4noctBI77zy3MbWPLpo',
    appId: '1:30448934988:ios:9ebc32e538b070d60394e9',
    messagingSenderId: '30448934988',
    projectId: 'driptock-dp',
    storageBucket: 'driptock-dp.firebasestorage.app',
    iosBundleId: 'com.example.dripTok',
  );

}